# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notgur', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notgur.Image'),
            preserve_default=False,
        ),
    ]
